INSERT INTO articulos (tipo, marca, modelo, precio) VALUES ('Camiseta', 'Nike', 'Air Max', 29.99);
INSERT INTO articulos (tipo, marca, modelo, precio) VALUES ('Camiseta', 'Adidas', 'Duo Pro', 19.95);
INSERT INTO articulos (tipo, marca, modelo, precio) VALUES ('Camiseta', 'Puma', 'Classic Fit', 24.99);
INSERT INTO articulos (tipo, marca, modelo, precio) VALUES ('Camiseta', 'Under Armour', 'Tech Tee', 34.99);
INSERT INTO articulos (tipo, marca, modelo, precio) VALUES ('Camiseta', 'Reebok', 'Essential Graphic', 17.50);
INSERT INTO articulos (tipo, marca, modelo, precio) VALUES ('Camiseta', 'New Balance', 'Performance Tech', 27.95);
INSERT INTO articulos (tipo, marca, modelo, precio) VALUES ('Camiseta', 'Fila', 'Heritage', 22.50);
INSERT INTO articulos (tipo, marca, modelo, precio) VALUES ('Camiseta', 'Lacoste', 'Sport Ultra Dry', 39.99);
INSERT INTO articulos (tipo, marca, modelo, precio) VALUES ('Camiseta', 'Converse', 'Chuck Patch', 19.99);
INSERT INTO articulos (tipo, marca, modelo, precio) VALUES ('Camiseta', 'Vans', 'Off The Wall', 29.95);
INSERT INTO articulos (tipo, marca, modelo, precio) VALUES ('Zapatillas', 'Nike', 'Air Max 270', 129.99);
INSERT INTO articulos (tipo, marca, modelo, precio) VALUES ('Zapatillas', 'Adidas', 'Ultraboost', 159.95);
INSERT INTO articulos (tipo, marca, modelo, precio) VALUES ('Zapatillas', 'Puma', 'RS-X', 89.99);
INSERT INTO articulos (tipo, marca, modelo, precio) VALUES ('Zapatillas', 'Under Armour', 'HOVR Sonic', 109.99);
INSERT INTO articulos (tipo, marca, modelo, precio) VALUES ('Zapatillas', 'Reebok', 'Classic Leather', 79.95);
INSERT INTO articulos (tipo, marca, modelo, precio) VALUES ('Zapatillas', 'New Balance', 'Fresh Foam 1080', 149.95);
INSERT INTO articulos (tipo, marca, modelo, precio) VALUES ('Zapatillas', 'Fila', 'Disruptor II', 79.99);
INSERT INTO articulos (tipo, marca, modelo, precio) VALUES ('Zapatillas', 'Lacoste', 'Carnaby Evo', 119.99);
INSERT INTO articulos (tipo, marca, modelo, precio) VALUES ('Zapatillas', 'Converse', 'Chuck Taylor All Star', 59.99);
INSERT INTO articulos (tipo, marca, modelo, precio) VALUES ('Zapatillas', 'Vans', 'Old Skool', 69.95);
INSERT INTO tiendas (nombre, tipo, calle, numero, email) VALUES ('Tienda A', 'Ropa', 'Calle Mayor', '10', 'tiendaA@example.com');
INSERT INTO tiendas (nombre, tipo, calle, numero, email) VALUES ('Tienda B', 'Electrónica', 'Avenida Libertad', '25', 'tiendaB@example.com');
INSERT INTO tiendas (nombre, tipo, calle, numero, email) VALUES ('Tienda C', 'Joyería', 'Calle Gran Vía', '15', 'tiendaC@example.com');
INSERT INTO tiendas (nombre, tipo, calle, numero, email) VALUES ('Tienda D', 'Muebles', 'Avenida Principal', '45', 'tiendaD@example.com');
INSERT INTO tiendas (nombre, tipo, calle, numero, email) VALUES ('Tienda E', 'Muebles', 'Calle del Sol', '8', 'tiendaE@example.com');
INSERT INTO tiendas (nombre, tipo, calle, numero, email) VALUES ('Tienda F', 'Deportes', 'Avenida Central', '30', 'tiendaF@example.com');
INSERT INTO tiendas (nombre, tipo, calle, numero, email) VALUES ('Tienda G', 'Librería', 'Calle del Paseo', '12', 'tiendaG@example.com');
INSERT INTO tiendas (nombre, tipo, calle, numero, email) VALUES ('Tienda H', 'Belleza', 'Avenida del Mar', '18', 'tiendaH@example.com');
INSERT INTO tiendas (nombre, tipo, calle, numero, email) VALUES ('Tienda I', 'Joyería', 'Calle de la Luna', '5', 'tiendaI@example.com');
INSERT INTO tiendas (nombre, tipo, calle, numero, email) VALUES ('Tienda J', 'Librería', 'Avenida del Sol', '22', 'tiendaJ@example.com');
INSERT INTO pedidos (referencia, descripcion, tienda_id) VALUES ('Referencia del primer pedido', 'Descripción del primer pedido', 1);
INSERT INTO pedidos (referencia, descripcion, tienda_id) VALUES ('Referencia del segundo pedido', 'Descripción del segundo pedido', 1);
